### ISSUE TITLE
Latest dependency versions causing build error

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#163]
The [last dependencies bump](https://github.com/gettypubs/quire-starter-theme/commit/4f9ae0f9eaa9f9b3a0a265bcfcb79152402e5e1e) in the starter theme seems to have caused some issues. When running `quire site` or `quire epub` we're seeing the below error around webpack-cli or clean-webpack-plugin. (The text below is from the Nelson-Atkins project, but I've seen the same issue across all of the projects I've tested.) The issue resolves when temporarily reverting the package.json file back to its earlier iteration and running `npm install` again to get the older versions of everything. I didn't test further than that.

```
quire site
⠼ Building theme assets.../Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack-cli/bin/cli.js:231
				throw err;
				^

Error: clean-webpack-plugin only accepts an options object. See:
            https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional
    at new CleanWebpackPlugin (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/clean-webpack-plugin/dist/clean-webpack-plugin.js:17:13)
    at Object.<anonymous> (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/webpack/webpack.config.prod.js:138:5)
    at Module._compile (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack-cli/bin/convert-argv.js:115:13)
    at requireConfig (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack-cli/bin/convert-argv.js:117:6)
    at /Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at yargs.parse (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack-cli/bin/cli.js:228:39)
    at Object.parse (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack-cli/bin/cli.js:206:8
    at Object.<anonymous> (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/stephanie/gitlocal/live/themes/quire-starter-theme/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
✖ Command failed: node_modules/.bin/webpack --config webpack/webpack.config.prod.js --output-public-path https://intranet.nelson-atkins.org/publications/catalog-french-paintings17/
null
```

**Comment by naeluh** [comment]
@geealbers I can make a patch for this

**Comment by geealbers** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/9cebe615fb026c6462c416b8630efbc6ee1cc8be
