### ISSUE TITLE
Preview Issue

### ISSUE THREAD

**Issue by beaaic** [gettypubs/quire#97]
Hi! I'm having an issue with the preview. I can't figure it out. Starting the quire preview command in the terminal, I'm getting following output:

Launching preview server
Navigate to http://localhost:1313 to see your changes.
Press Control+C or type "quire stop" to stop the preview.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/.bin/webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Thanks,
Bea

**Comment by naeluh** [comment]
Hi @beaaic were you able to fix this?

**Comment by beaaic** [comment]
Hi Nick,

Yes, thanks! There was a mistake in my config file, which I found right after posting.

**Comment by beaaic** [comment]
Hi @naeluh, 
Yes, thanks! There was a mistake in my config file, which I found right after posting.
